# Generated by Django 4.2.1 on 2023-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dataset_options_alter_dataset_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_file', models.FilePathField(blank=True, path='media')),
            ],
            options={
                'verbose_name': 'модель машинного обучения',
                'verbose_name_plural': 'модели машинного обучения',
                'db_table': 'ml_model',
            },
        ),
    ]
